
// AUTO-GENERATED BY scripts/generate-data.js
// DO NOT EDIT MANUALLY - UPDATE info.txt FILES INSTEAD

import proj_0_A from '../../portfolio-content/Projets/Commercial/Converse/A.jpg';
import proj_0_B from '../../portfolio-content/Projets/Commercial/Converse/B.jpg';
import proj_0_C from '../../portfolio-content/Projets/Commercial/Converse/C.jpg';
import proj_0_D from '../../portfolio-content/Projets/Commercial/Converse/D.jpg';
import proj_1_A from '../../portfolio-content/Projets/Commercial/Fishermen Friends/A.jpg';
import proj_1_B from '../../portfolio-content/Projets/Commercial/Fishermen Friends/B.jpg';
import proj_1_C from '../../portfolio-content/Projets/Commercial/Fishermen Friends/C.mp4';
import proj_1_D from '../../portfolio-content/Projets/Commercial/Fishermen Friends/D.mp4';
import proj_1_E from '../../portfolio-content/Projets/Commercial/Fishermen Friends/E.mp4';
import proj_2_A from '../../portfolio-content/Projets/Commercial/The Street Partners/A.jpg';
import proj_2_B from '../../portfolio-content/Projets/Commercial/The Street Partners/B.mp4';
import proj_2_C from '../../portfolio-content/Projets/Commercial/The Street Partners/C.jpg';
import proj_2_D from '../../portfolio-content/Projets/Commercial/The Street Partners/D.jpg';
import proj_2_E from '../../portfolio-content/Projets/Commercial/The Street Partners/E.mp4';
import proj_2_F from '../../portfolio-content/Projets/Commercial/The Street Partners/F.jpg';
import proj_3_A from '../../portfolio-content/Projets/Documentary/Bergers des Abeilles/A.jpg';
import proj_3_B from '../../portfolio-content/Projets/Documentary/Bergers des Abeilles/B.jpg';
import proj_3_C from '../../portfolio-content/Projets/Documentary/Bergers des Abeilles/C.mp4';
import proj_3_D from '../../portfolio-content/Projets/Documentary/Bergers des Abeilles/D.jpg';
import proj_4_A from '../../portfolio-content/Projets/Documentary/Des collines aux machines/A.jpg';
import proj_4_B from '../../portfolio-content/Projets/Documentary/Des collines aux machines/B.mp4';
import proj_4_C from '../../portfolio-content/Projets/Documentary/Des collines aux machines/C.jpg';
import proj_4_D from '../../portfolio-content/Projets/Documentary/Des collines aux machines/D.mp4';
import proj_4_E from '../../portfolio-content/Projets/Documentary/Des collines aux machines/E.jpg';
import proj_4_F from '../../portfolio-content/Projets/Documentary/Des collines aux machines/F.jpg';
import proj_5_A from '../../portfolio-content/Projets/Music Video/Bonne Santé – Visualiser/A.jpg';
import proj_5_B from '../../portfolio-content/Projets/Music Video/Bonne Santé – Visualiser/B.mp4';
import proj_5_C from '../../portfolio-content/Projets/Music Video/Bonne Santé – Visualiser/C.jpg';
import proj_5_D from '../../portfolio-content/Projets/Music Video/Bonne Santé – Visualiser/D.jpg';
import proj_5_E from '../../portfolio-content/Projets/Music Video/Bonne Santé – Visualiser/E.jpg';
import proj_6_A from '../../portfolio-content/Projets/Music Video/Jamais/A.jpg';
import proj_6_B from '../../portfolio-content/Projets/Music Video/Jamais/B.jpg';
import proj_6_C from '../../portfolio-content/Projets/Music Video/Jamais/C.mp4';
import proj_6_D from '../../portfolio-content/Projets/Music Video/Jamais/D.jpg';
import proj_6_E from '../../portfolio-content/Projets/Music Video/Jamais/E.mp4';
import proj_7_cover from '../../portfolio-content/Projets/Music Video/Komani/cover.jpg';
import proj_7_A from '../../portfolio-content/Projets/Music Video/Komani/A.jpg';
import proj_7_B from '../../portfolio-content/Projets/Music Video/Komani/B.mp4';
import proj_7_C from '../../portfolio-content/Projets/Music Video/Komani/C.jpg';
import proj_7_D from '../../portfolio-content/Projets/Music Video/Komani/D.jpg';
import proj_7_E from '../../portfolio-content/Projets/Music Video/Komani/E.mp4';
import proj_8_A from '../../portfolio-content/Projets/Music Video/Level Up/A.jpg';
import proj_8_B from '../../portfolio-content/Projets/Music Video/Level Up/B.jpg';
import proj_8_C from '../../portfolio-content/Projets/Music Video/Level Up/C.mp4';
import proj_8_D from '../../portfolio-content/Projets/Music Video/Level Up/D.jpg';
import proj_8_E from '../../portfolio-content/Projets/Music Video/Level Up/E.jpg';
import proj_9_A from '../../portfolio-content/Projets/Short Film/Dîner d’Affaire/A.jpg';
import proj_9_B from '../../portfolio-content/Projets/Short Film/Dîner d’Affaire/B.jpg';
import proj_9_C from '../../portfolio-content/Projets/Short Film/Dîner d’Affaire/C.mp4';
import proj_9_D from '../../portfolio-content/Projets/Short Film/Dîner d’Affaire/D.jpg';
import proj_9_E from '../../portfolio-content/Projets/Short Film/Dîner d’Affaire/E.jpg';
import proj_10_A from '../../portfolio-content/Projets/Short Film/Fort Intérieur/A.jpg';
import proj_10_B from '../../portfolio-content/Projets/Short Film/Fort Intérieur/B.jpg';
import proj_10_C from '../../portfolio-content/Projets/Short Film/Fort Intérieur/C.jpg';
import proj_10_D from '../../portfolio-content/Projets/Short Film/Fort Intérieur/D.mp4';
import proj_10_E from '../../portfolio-content/Projets/Short Film/Fort Intérieur/E.jpg';
import proj_10_F from '../../portfolio-content/Projets/Short Film/Fort Intérieur/F.jpg';
import proj_11_A from '../../portfolio-content/Projets/Short Film/Le miroir des générations/A.jpg';
import proj_11_B from '../../portfolio-content/Projets/Short Film/Le miroir des générations/B.mp4';
import proj_11_C from '../../portfolio-content/Projets/Short Film/Le miroir des générations/C.jpg';
import proj_12_A from '../../portfolio-content/Projets/Short Film/Léo/A.jpg';
import proj_12_B from '../../portfolio-content/Projets/Short Film/Léo/B.jpg';
import proj_13_A from '../../portfolio-content/Projets/Short Film/Marcello/A.jpg';
import proj_13_B from '../../portfolio-content/Projets/Short Film/Marcello/B.jpg';
import proj_13_C from '../../portfolio-content/Projets/Short Film/Marcello/C.jpg';
import proj_14_A from '../../portfolio-content/Projets/Short Film/Nouvelle Ecoute/A.jpg';
import proj_14_B from '../../portfolio-content/Projets/Short Film/Nouvelle Ecoute/B.mp4';
import proj_14_C from '../../portfolio-content/Projets/Short Film/Nouvelle Ecoute/C.jpg';
import proj_14_D from '../../portfolio-content/Projets/Short Film/Nouvelle Ecoute/D.jpg';
import proj_15_A from '../../portfolio-content/Projets/Short Film/Parles-moi/A.jpg';
import proj_15_B from '../../portfolio-content/Projets/Short Film/Parles-moi/B.mp4';
import proj_15_C from '../../portfolio-content/Projets/Short Film/Parles-moi/C.jpg';
import proj_15_D from '../../portfolio-content/Projets/Short Film/Parles-moi/D.mp4';
import proj_16_A from '../../portfolio-content/Projets/Social Media/Nassim Boukrouh/A.jpg';
import proj_16_B from '../../portfolio-content/Projets/Social Media/Nassim Boukrouh/B.jpg';
import proj_16_C from '../../portfolio-content/Projets/Social Media/Nassim Boukrouh/C.mp4';
import proj_16_D from '../../portfolio-content/Projets/Social Media/Nassim Boukrouh/D.mp4';
import proj_16_E from '../../portfolio-content/Projets/Social Media/Nassim Boukrouh/E.mp4';
import proj_16_F from '../../portfolio-content/Projets/Social Media/Nassim Boukrouh/F.mp4';
import proj_16_G from '../../portfolio-content/Projets/Social Media/Nassim Boukrouh/G.jpg';
import proj_17_A from '../../portfolio-content/Projets/Weddings/M&L/A.jpg';
import proj_17_B from '../../portfolio-content/Projets/Weddings/M&L/B.jpg';
import proj_17_C from '../../portfolio-content/Projets/Weddings/M&L/C.mp4';
import proj_17_D from '../../portfolio-content/Projets/Weddings/M&L/D.jpg';
import proj_17_E from '../../portfolio-content/Projets/Weddings/M&L/E.jpg';
import proj_17_F from '../../portfolio-content/Projets/Weddings/M&L/F.mp4';
import reel_1 from '../../portfolio-content/Instagram Reel/1.mp4';
import reel_poster_1 from '../../portfolio-content/Instagram Reel/1.jpg';
import reel_2 from '../../portfolio-content/Instagram Reel/2.mp4';
import reel_poster_2 from '../../portfolio-content/Instagram Reel/2.jpg';
import reel_3 from '../../portfolio-content/Instagram Reel/3.mp4';
import reel_poster_3 from '../../portfolio-content/Instagram Reel/3.jpg';
import reel_4 from '../../portfolio-content/Instagram Reel/4.mp4';
import reel_poster_4 from '../../portfolio-content/Instagram Reel/4.jpg';
import reel_5 from '../../portfolio-content/Instagram Reel/5.mp4';
import reel_poster_5 from '../../portfolio-content/Instagram Reel/5.jpg';
import reel_6 from '../../portfolio-content/Instagram Reel/6.mp4';
import reel_poster_6 from '../../portfolio-content/Instagram Reel/6.jpg';
import reel_7 from '../../portfolio-content/Instagram Reel/7.mp4';
import reel_poster_7 from '../../portfolio-content/Instagram Reel/7.jpg';
import reel_8 from '../../portfolio-content/Instagram Reel/8.mp4';
import reel_poster_8 from '../../portfolio-content/Instagram Reel/8.jpg';
import reel_9 from '../../portfolio-content/Instagram Reel/9.mp4';
import reel_poster_9 from '../../portfolio-content/Instagram Reel/9.jpg';
import reel_10 from '../../portfolio-content/Instagram Reel/10.mp4';
import reel_poster_10 from '../../portfolio-content/Instagram Reel/10.jpg';
import reel_11 from '../../portfolio-content/Instagram Reel/11.mp4';
import reel_poster_11 from '../../portfolio-content/Instagram Reel/11.jpg';
import reel_12 from '../../portfolio-content/Instagram Reel/12.mp4';
import reel_poster_12 from '../../portfolio-content/Instagram Reel/12.jpg';
import reel_13 from '../../portfolio-content/Instagram Reel/13.mp4';
import reel_poster_13 from '../../portfolio-content/Instagram Reel/13.jpg';
import reel_14 from '../../portfolio-content/Instagram Reel/14.mp4';
import reel_poster_14 from '../../portfolio-content/Instagram Reel/14.jpg';
import reel_15 from '../../portfolio-content/Instagram Reel/15.mp4';
import reel_poster_15 from '../../portfolio-content/Instagram Reel/15.jpg';
import reel_16 from '../../portfolio-content/Instagram Reel/16.mp4';
import reel_poster_16 from '../../portfolio-content/Instagram Reel/16.jpg';

export const projects = [
    {
        "id": 100,
        "title": "Converse",
        "category": "commercial",
        "role": "spark_me",
        "date": {
            "fr": "December 2025",
            "en": "December 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Publicité (Spec Ad) réalisée par une équipe de l'ESRA. Un tournage entièrement sous la pluie, nécessitant une gestion électrique rigoureuse et sécurisée. J'y ai travaillé comme renfort Électro.",
            "en": "Spec ad by an ESRA team, shot entirely under rain. Required strict, safe electrical handling. I worked as Electrician reinforcement."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_0_A,
        "collection": [
            {
                "type": "image",
                "src": proj_0_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_0_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_0_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_0_D,
                "poster": ""
            }
        ]
    },
    {
        "id": 101,
        "title": "Fishermen Friends",
        "category": "commercial",
        "role": "grip_me",
        "date": {
            "fr": "December 2025",
            "en": "December 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Publicité (Spec Ad) produite par une équipe de l'ESRA, tournée entièrement en studio. Un décor surélevé qui exigeait une grande rigueur technique. J'ai occupé les postes d'Électro et Machiniste.",
            "en": "Studio-shot ESRA spec ad with an elevated set requiring technical precision. I worked as both Electrician and Grip."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_1_A,
        "collection": [
            {
                "type": "image",
                "src": proj_1_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_1_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_1_C,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_1_D,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_1_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 102,
        "title": "The Street Partners",
        "category": "commercial",
        "role": "dop_me",
        "date": {
            "fr": "July 2025",
            "en": "July 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Publicité pour The Street Partners. Une approche corporate moderne axée sur le branding et une image soignée. J'étais Directeur de la Photographie.",
            "en": "Corporate commercial for The Street Partners, built with a modern visual identity focused on clean branding. I was Director of Photography."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_2_A,
        "collection": [
            {
                "type": "image",
                "src": proj_2_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_2_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_2_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_2_D,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_2_E,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_2_F,
                "poster": ""
            }
        ]
    },
    {
        "id": 103,
        "title": "Bergers des Abeilles",
        "category": "documentary",
        "role": "dop_me",
        "date": {
            "fr": "April 2025",
            "en": "April 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Documentaire de festival suivant des apiculteurs et le rôle vital des abeilles. Un film ancré dans le travail de terrain et l'artisanat traditionnel. J'étais Directeur de la Photographie et Cadreur.",
            "en": "Festival documentary following beekeepers and the crucial role of bees. Rooted in real fieldwork and traditional craft. I worked as Director of Photography and Camera Operator."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_3_A,
        "collection": [
            {
                "type": "image",
                "src": proj_3_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_3_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_3_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_3_D,
                "poster": ""
            }
        ]
    },
    {
        "id": 104,
        "title": "Des collines aux machines",
        "category": "documentary",
        "role": "director_me",
        "date": {
            "fr": "May 2025",
            "en": "May 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Documentaire de festival sur les bergers modernes et les défis qu'ils affrontent aujourd'hui. Un regard authentique sur la tension entre tradition et modernité. J'ai réalisé le film.",
            "en": "Festival documentary about modern shepherds facing the tension between tradition and technological evolution. I directed the film."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_4_A,
        "collection": [
            {
                "type": "image",
                "src": proj_4_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_4_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_4_C,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_4_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_4_E,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_4_F,
                "poster": ""
            }
        ]
    },
    {
        "id": 105,
        "title": "Bonne Santé – Visualiser",
        "category": "music_video",
        "role": "dop_me",
        "date": {
            "fr": "August 2025",
            "en": "August 2025"
        },
        "status": "Delivered",
        "link": "https://youtu.be/tgxDICtOiC8?si=0VFyGOwveazqQdd4",
        "desc": {
            "fr": "Visualizer musical pour Faz’r Elengi. Un concept épuré et ciblé, centré sur la performance et l'esthétique. J'étais Directeur de la Photographie.",
            "en": "Music visualizer for Faz’r Elengi, built around a clean performance-driven aesthetic. I worked as Director of Photography."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_5_A,
        "collection": [
            {
                "type": "image",
                "src": proj_5_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_5_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_5_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_5_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_5_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 106,
        "title": "Jamais",
        "category": "music_video",
        "role": "dop_me",
        "date": {
            "fr": "November 2024",
            "en": "November 2024"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Clip vidéo pour Faz’r Elengi tourné en studio d'enregistrement. Une création simple mais efficace avec très peu de matériel. J'étais Directeur de la Photographie.",
            "en": "Minimalist studio-shot music video for Faz’r Elengi, created with very limited equipment. I worked as Director of Photography."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_6_A,
        "collection": [
            {
                "type": "image",
                "src": proj_6_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_6_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_6_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_6_D,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_6_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 107,
        "title": "Komani",
        "category": "music_video",
        "role": "director_me",
        "date": {
            "fr": "August 2025",
            "en": "August 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Clip vidéo pour l'artiste Faz’r Elengi. Tourné dans quatre lieux différents, avec notamment ma première gestion de voitures de drift sur le plateau. J'ai réalisé le clip et supervisé toute la mise en scène.",
            "en": "Music video for Faz’r Elengi shot in four locations, including my first experience supervising drift cars on set. I directed and handled staging."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_7_cover,
        "collection": [
            {
                "type": "image",
                "src": proj_7_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_7_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_7_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_7_D,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_7_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 108,
        "title": "Level Up",
        "category": "music_video",
        "role": "cam_dir_me",
        "date": {
            "fr": "September 2025",
            "en": "September 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Clip vidéo pour l'artiste VIO. Un univers dynamique mêlant danse, rythme et une identité visuelle marquante. J'ai réalisé le vidéo.",
            "en": "Energetic music video for VIO, mixing dance, rhythm and strong visual identity. I directed the video and operated camera."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_8_A,
        "collection": [
            {
                "type": "image",
                "src": proj_8_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_8_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_8_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_8_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_8_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 109,
        "title": "Dîner d’Affaire",
        "category": "short_film",
        "role": "spark_me",
        "date": {
            "fr": "November 2025",
            "en": "November 2025"
        },
        "status": "In Distribution",
        "link": "https://youtu.be/XE4fg93ZOfc",
        "desc": {
            "fr": "Court-métrage tourné pour le 48h Côte d’Azur, sur le thème « Repas ». L'histoire suit une artiste qui confronte son producteur toxique. Initialement engagé comme Électro, j'ai finalement pris en charge toute la machinerie durant le tournage.",
            "en": "Short film for the 48h Côte d’Azur contest, on the theme “Dinner.” The story follows an artist confronting her toxic producer. Initially hired as Electrician, I ended up taking full charge of the grip department on set."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_9_A,
        "collection": [
            {
                "type": "image",
                "src": proj_9_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_9_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_9_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_9_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_9_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 110,
        "title": "Fort Intérieur",
        "category": "short_film",
        "role": "dop_me",
        "date": {
            "fr": "June 2025",
            "en": "June 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Court-métrage d'un étudiant de Studio M. L'histoire d'un jeune homme héritant de la maison familiale et confrontant un traumatisme enfoui. J'ai travaillé comme Directeur de la Photographie.",
            "en": "Short film by a Studio M student. The story follows a young man confronting inherited trauma in his family home. I was Director of Photography."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_10_A,
        "collection": [
            {
                "type": "image",
                "src": proj_10_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_10_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_10_C,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_10_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_10_E,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_10_F,
                "poster": ""
            }
        ]
    },
    {
        "id": 111,
        "title": "Le miroir des générations",
        "category": "short_film",
        "role": "dop_me",
        "date": {
            "fr": "December 2025",
            "en": "December 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Court-métrage réalisé pour le Nikon Film Festival sur le thème « Le Feu ». Le film explore la transmission, la perception de soi et les liens intergénérationnels. J'étais Directeur de la Photographie.",
            "en": "Short film for the Nikon Film Festival, on the theme “Beauty.” The film explores transmission, self-perception and generational transitions. I was Director of Photography."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_11_A,
        "collection": [
            {
                "type": "image",
                "src": proj_11_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_11_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_11_C,
                "poster": ""
            }
        ]
    },
    {
        "id": 112,
        "title": "Léo",
        "category": "short_film",
        "role": "camera_op_me",
        "date": {
            "fr": "December 2024",
            "en": "December 2024"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Court-métrage pour le Nikon Film Festival 2024, thème « Super-héros ». Un jeune garçon handicapé imagine marcher comme dans ses comics préférés. J'étais Cadreur.",
            "en": "Short film for the 2024 Nikon Film Festival, theme “Superhero.” A disabled boy imagines himself walking like the characters from his comics. I worked as Camera Operator."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_12_A,
        "collection": [
            {
                "type": "image",
                "src": proj_12_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_12_B,
                "poster": ""
            }
        ]
    },
    {
        "id": 113,
        "title": "Marcello",
        "category": "short_film",
        "role": "key_grip_me",
        "date": {
            "fr": "September 2025",
            "en": "September 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Court-métrage réalisé pour des festivals, produit en association. L'histoire plonge dans le monde du journalisme niçois des années 1980. J'y ai travaillé comme Chef Machiniste, encadrant une équipe de 2 à 4 techniciens, de la pré-production à l'intense travail de plateau.",
            "en": "Short film made for festivals under a non-profit association. Set in the world of Nice journalism in the 1980s. I worked as Key Grip, managing a team of 2 to 4 technicians through prep and a demanding shoot."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_13_A,
        "collection": [
            {
                "type": "image",
                "src": proj_13_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_13_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_13_C,
                "poster": ""
            }
        ]
    },
    {
        "id": 114,
        "title": "Nouvelle Ecoute",
        "category": "short_film",
        "role": "camera_op_me",
        "date": {
            "fr": "November 2025",
            "en": "November 2025"
        },
        "status": "Delivered",
        "link": "https://www.youtube.com/watch?v=0o7v2v1dPTc",
        "desc": {
            "fr": "Court-métrage pour le Festival TousHanscene. Un jeune sourd perd ses appareils auditifs et fait face à une journée d'obstacles. J'étais Cadreur.",
            "en": "Short film for the TousHanscene Festival. A deaf young man loses his hearing aids and must navigate a difficult day. I worked as Camera Operator."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_14_A,
        "collection": [
            {
                "type": "image",
                "src": proj_14_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_14_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_14_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_14_D,
                "poster": ""
            }
        ]
    },
    {
        "id": 115,
        "title": "Parles-moi",
        "category": "short_film",
        "role": "gaffer_me",
        "date": {
            "fr": "November 2025",
            "en": "November 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Court-métrage pour le Nikon 2025. Un couple déstabilisé par une hospitalisation soudaine, naviguant entre fragilité et intimité. J'étais Chef Électricien (Gaffer), créant une lumière douce et émotionnelle.",
            "en": "Short film for the Nikon Film Festival 2025, theme “Beauty.” A couple faces emotional fragility after a sudden hospitalisation. I crafted a soft, intimate lighting setup."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_15_A,
        "collection": [
            {
                "type": "image",
                "src": proj_15_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_15_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_15_C,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_15_D,
                "poster": ""
            }
        ]
    },
    {
        "id": 116,
        "title": "Nassim Boukrouh",
        "category": "social_media",
        "role": "camera_op_me",
        "date": {
            "fr": "Current",
            "en": "Current"
        },
        "status": "Ongoing",
        "link": "https://youtube.com/@nassimboukrouh?si=zvPcrKR7CY8gO8xt",
        "desc": {
            "fr": "Série de vidéos YouTube pour un créateur de contenu immobilier. Tournages mobiles à travers la Suisse dans des environnements variés. J'étais Cadreur.",
            "en": "YouTube real-estate content shot across Switzerland in various environments. I worked as Camera Operator."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_16_A,
        "collection": [
            {
                "type": "image",
                "src": proj_16_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_16_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_16_C,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_16_D,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_16_E,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_16_F,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_16_G,
                "poster": ""
            }
        ]
    },
    {
        "id": 117,
        "title": "M&L",
        "category": "wedding",
        "role": "dop_me",
        "date": {
            "fr": "July 2025",
            "en": "July 2025"
        },
        "status": "Delivered",
        "link": "https://youtu.be/P_eesdexjfs?si=2KAz39jzmFFlfHg_",
        "desc": {
            "fr": "Film de mariage tourné au Mas des 5 Fontaines. Un mélange entre captation documentaire et approche cinématographique. J'étais Cadreur et Directeur de la Photographie.",
            "en": "Wedding film shot at Mas des 5 Fontaines, blending documentary capture and cinematic language. I worked as Camera Operator and Director of Photography."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_17_A,
        "collection": [
            {
                "type": "image",
                "src": proj_17_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_17_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_17_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_17_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_17_E,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_17_F,
                "poster": ""
            }
        ]
    },
    {
        "id": 10,
        "title": "Instagram Reels",
        "category": "social_media",
        "role": "content_creation_me",
        "date": {
            "fr": "2025",
            "en": "2025"
        },
        "status": "Online",
        "link": "",
        "desc": {
            "en": "A collection of dynamic, high-engagement reels created for various brands and personal projects.",
            "fr": "Une collection de reels dynamiques créés pour diverses marques et projets personnels."
        },
        "media": "/portfolio/assets/projects/instagram-3d-final.png",
        "type": "collection",
        "collection": [
            {
                "type": "video",
                "src": reel_1,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_1
            },
            {
                "type": "video",
                "src": reel_2,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_2
            },
            {
                "type": "video",
                "src": reel_3,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_3
            },
            {
                "type": "video",
                "src": reel_4,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_4
            },
            {
                "type": "video",
                "src": reel_5,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_5
            },
            {
                "type": "video",
                "src": reel_6,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_6
            },
            {
                "type": "video",
                "src": reel_7,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_7
            },
            {
                "type": "video",
                "src": reel_8,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_8
            },
            {
                "type": "video",
                "src": reel_9,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_9
            },
            {
                "type": "video",
                "src": reel_10,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_10
            },
            {
                "type": "video",
                "src": reel_11,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_11
            },
            {
                "type": "video",
                "src": reel_12,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_12
            },
            {
                "type": "video",
                "src": reel_13,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_13
            },
            {
                "type": "video",
                "src": reel_14,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_14
            },
            {
                "type": "video",
                "src": reel_15,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_15
            },
            {
                "type": "video",
                "src": reel_16,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_16
            }
        ]
    }
];
