
// AUTO-GENERATED BY scripts/generate-data.js
// DO NOT EDIT MANUALLY - UPDATE info.txt FILES INSTEAD

import proj_0_A from '../../lucas-content/Projets/Commercial/Converse/A.jpg';
import proj_0_B from '../../lucas-content/Projets/Commercial/Converse/B.jpg';
import proj_0_C from '../../lucas-content/Projets/Commercial/Converse/C.jpg';
import proj_0_D from '../../lucas-content/Projets/Commercial/Converse/D.jpg';
import proj_1_A from '../../lucas-content/Projets/Commercial/Fishermen Friends/A.jpg';
import proj_1_B from '../../lucas-content/Projets/Commercial/Fishermen Friends/B.mp4';
import proj_1_C from '../../lucas-content/Projets/Commercial/Fishermen Friends/C.jpg';
import proj_1_D from '../../lucas-content/Projets/Commercial/Fishermen Friends/D.jpg';
import proj_1_E from '../../lucas-content/Projets/Commercial/Fishermen Friends/E.mp4';
import proj_1_F from '../../lucas-content/Projets/Commercial/Fishermen Friends/F.jpg';
import proj_1_G from '../../lucas-content/Projets/Commercial/Fishermen Friends/G.jpg';
import proj_1_H from '../../lucas-content/Projets/Commercial/Fishermen Friends/H.jpg';
import proj_1_I from '../../lucas-content/Projets/Commercial/Fishermen Friends/I.jpg';
import proj_1_J from '../../lucas-content/Projets/Commercial/Fishermen Friends/J.mp4';
import proj_2_A from '../../lucas-content/Projets/Commercial/The Street Partners/A.jpg';
import proj_2_B from '../../lucas-content/Projets/Commercial/The Street Partners/B.mp4';
import proj_2_C from '../../lucas-content/Projets/Commercial/The Street Partners/C.jpg';
import proj_2_D from '../../lucas-content/Projets/Commercial/The Street Partners/D.jpg';
import proj_2_E from '../../lucas-content/Projets/Commercial/The Street Partners/E.mp4';
import proj_2_F from '../../lucas-content/Projets/Commercial/The Street Partners/F.jpg';
import proj_3_A from '../../lucas-content/Projets/Documentary/Bergers des Abeilles/A.jpg';
import proj_3_B from '../../lucas-content/Projets/Documentary/Bergers des Abeilles/B.jpg';
import proj_3_C from '../../lucas-content/Projets/Documentary/Bergers des Abeilles/C.mp4';
import proj_3_D from '../../lucas-content/Projets/Documentary/Bergers des Abeilles/D.jpg';
import proj_4_A from '../../lucas-content/Projets/Documentary/Des collines aux machines/A.jpg';
import proj_4_B from '../../lucas-content/Projets/Documentary/Des collines aux machines/B.mp4';
import proj_4_C from '../../lucas-content/Projets/Documentary/Des collines aux machines/C.jpg';
import proj_4_D from '../../lucas-content/Projets/Documentary/Des collines aux machines/D.mp4';
import proj_4_E from '../../lucas-content/Projets/Documentary/Des collines aux machines/E.jpg';
import proj_4_F from '../../lucas-content/Projets/Documentary/Des collines aux machines/F.jpg';
import proj_5_A from '../../lucas-content/Projets/Music Video/Bonne Santé – Visualiser/A.jpg';
import proj_5_B from '../../lucas-content/Projets/Music Video/Bonne Santé – Visualiser/B.mp4';
import proj_5_C from '../../lucas-content/Projets/Music Video/Bonne Santé – Visualiser/C.jpg';
import proj_5_D from '../../lucas-content/Projets/Music Video/Bonne Santé – Visualiser/D.jpg';
import proj_5_E from '../../lucas-content/Projets/Music Video/Bonne Santé – Visualiser/E.jpg';
import proj_6_A from '../../lucas-content/Projets/Music Video/Jamais/A.jpg';
import proj_6_B from '../../lucas-content/Projets/Music Video/Jamais/B.jpg';
import proj_6_C from '../../lucas-content/Projets/Music Video/Jamais/C.mp4';
import proj_6_D from '../../lucas-content/Projets/Music Video/Jamais/D.jpg';
import proj_6_E from '../../lucas-content/Projets/Music Video/Jamais/E.mp4';
import proj_7_cover from '../../lucas-content/Projets/Music Video/Komani/cover.jpg';
import proj_7_A from '../../lucas-content/Projets/Music Video/Komani/A.jpg';
import proj_7_B from '../../lucas-content/Projets/Music Video/Komani/B.mp4';
import proj_7_C from '../../lucas-content/Projets/Music Video/Komani/C.jpg';
import proj_7_D from '../../lucas-content/Projets/Music Video/Komani/D.jpg';
import proj_7_E from '../../lucas-content/Projets/Music Video/Komani/E.mp4';
import proj_8_A from '../../lucas-content/Projets/Music Video/Level Up/A.jpg';
import proj_8_B from '../../lucas-content/Projets/Music Video/Level Up/B.jpg';
import proj_8_C from '../../lucas-content/Projets/Music Video/Level Up/C.mp4';
import proj_8_D from '../../lucas-content/Projets/Music Video/Level Up/D.jpg';
import proj_8_E from '../../lucas-content/Projets/Music Video/Level Up/E.jpg';
import proj_9_A from '../../lucas-content/Projets/Short Film/Dîner d’Affaire/A.jpg';
import proj_9_B from '../../lucas-content/Projets/Short Film/Dîner d’Affaire/B.jpg';
import proj_9_C from '../../lucas-content/Projets/Short Film/Dîner d’Affaire/C.mp4';
import proj_9_D from '../../lucas-content/Projets/Short Film/Dîner d’Affaire/D.jpg';
import proj_9_E from '../../lucas-content/Projets/Short Film/Dîner d’Affaire/E.jpg';
import proj_10_A from '../../lucas-content/Projets/Short Film/Fort Intérieur/A.jpg';
import proj_10_B from '../../lucas-content/Projets/Short Film/Fort Intérieur/B.jpg';
import proj_10_C from '../../lucas-content/Projets/Short Film/Fort Intérieur/C.jpg';
import proj_10_D from '../../lucas-content/Projets/Short Film/Fort Intérieur/D.mp4';
import proj_10_E from '../../lucas-content/Projets/Short Film/Fort Intérieur/E.jpg';
import proj_10_F from '../../lucas-content/Projets/Short Film/Fort Intérieur/F.jpg';
import proj_11_A from '../../lucas-content/Projets/Short Film/Léo/A.jpg';
import proj_11_B from '../../lucas-content/Projets/Short Film/Léo/B.jpg';
import proj_12_A from '../../lucas-content/Projets/Short Film/Marcello/A.jpg';
import proj_12_B from '../../lucas-content/Projets/Short Film/Marcello/B.jpg';
import proj_12_C from '../../lucas-content/Projets/Short Film/Marcello/C.jpg';
import proj_13_A from '../../lucas-content/Projets/Short Film/Nouvelle Ecoute/A.jpg';
import proj_13_B from '../../lucas-content/Projets/Short Film/Nouvelle Ecoute/B.mp4';
import proj_13_C from '../../lucas-content/Projets/Short Film/Nouvelle Ecoute/C.jpg';
import proj_13_D from '../../lucas-content/Projets/Short Film/Nouvelle Ecoute/D.jpg';
import proj_14_A from '../../lucas-content/Projets/Short Film/Parles-moi/A.jpg';
import proj_14_B from '../../lucas-content/Projets/Short Film/Parles-moi/B.mp4';
import proj_14_C from '../../lucas-content/Projets/Short Film/Parles-moi/C.jpg';
import proj_14_D from '../../lucas-content/Projets/Short Film/Parles-moi/D.mp4';
import proj_15_A from '../../lucas-content/Projets/Short Film/Transmission/A.jpg';
import proj_15_B from '../../lucas-content/Projets/Short Film/Transmission/B.mp4';
import proj_15_C from '../../lucas-content/Projets/Short Film/Transmission/C.jpg';
import proj_15_D from '../../lucas-content/Projets/Short Film/Transmission/D.jpg';
import proj_15_F from '../../lucas-content/Projets/Short Film/Transmission/F.jpg';
import proj_15_G from '../../lucas-content/Projets/Short Film/Transmission/G.jpg';
import proj_15_H from '../../lucas-content/Projets/Short Film/Transmission/H.jpg';
import proj_16_A from '../../lucas-content/Projets/Social Media/Nassim Boukrouh/A.jpg';
import proj_16_B from '../../lucas-content/Projets/Social Media/Nassim Boukrouh/B.jpg';
import proj_16_C from '../../lucas-content/Projets/Social Media/Nassim Boukrouh/C.mp4';
import proj_16_D from '../../lucas-content/Projets/Social Media/Nassim Boukrouh/D.mp4';
import proj_16_E from '../../lucas-content/Projets/Social Media/Nassim Boukrouh/E.mp4';
import proj_16_F from '../../lucas-content/Projets/Social Media/Nassim Boukrouh/F.mp4';
import proj_16_G from '../../lucas-content/Projets/Social Media/Nassim Boukrouh/G.jpg';
import proj_17_A from '../../lucas-content/Projets/Weddings/M&L/A.jpg';
import proj_17_B from '../../lucas-content/Projets/Weddings/M&L/B.jpg';
import proj_17_C from '../../lucas-content/Projets/Weddings/M&L/C.mp4';
import proj_17_D from '../../lucas-content/Projets/Weddings/M&L/D.jpg';
import proj_17_E from '../../lucas-content/Projets/Weddings/M&L/E.jpg';
import proj_17_F from '../../lucas-content/Projets/Weddings/M&L/F.mp4';
import reel_1 from '../../lucas-content/Instagram Reel/1.mp4';
import reel_poster_1 from '../../lucas-content/Instagram Reel/1.jpg';
import reel_2 from '../../lucas-content/Instagram Reel/2.mp4';
import reel_poster_2 from '../../lucas-content/Instagram Reel/2.jpg';
import reel_3 from '../../lucas-content/Instagram Reel/3.mp4';
import reel_poster_3 from '../../lucas-content/Instagram Reel/3.jpg';
import reel_4 from '../../lucas-content/Instagram Reel/4.mp4';
import reel_poster_4 from '../../lucas-content/Instagram Reel/4.jpg';
import reel_5 from '../../lucas-content/Instagram Reel/5.mp4';
import reel_poster_5 from '../../lucas-content/Instagram Reel/5.jpg';
import reel_6 from '../../lucas-content/Instagram Reel/6.mp4';
import reel_poster_6 from '../../lucas-content/Instagram Reel/6.jpg';
import reel_7 from '../../lucas-content/Instagram Reel/7.mp4';
import reel_poster_7 from '../../lucas-content/Instagram Reel/7.jpg';
import reel_8 from '../../lucas-content/Instagram Reel/8.mp4';
import reel_poster_8 from '../../lucas-content/Instagram Reel/8.jpg';
import reel_9 from '../../lucas-content/Instagram Reel/9.mp4';
import reel_poster_9 from '../../lucas-content/Instagram Reel/9.jpg';
import reel_10 from '../../lucas-content/Instagram Reel/10.mp4';
import reel_poster_10 from '../../lucas-content/Instagram Reel/10.jpg';
import reel_11 from '../../lucas-content/Instagram Reel/11.mp4';
import reel_poster_11 from '../../lucas-content/Instagram Reel/11.jpg';
import reel_12 from '../../lucas-content/Instagram Reel/12.mp4';
import reel_poster_12 from '../../lucas-content/Instagram Reel/12.jpg';
import reel_13 from '../../lucas-content/Instagram Reel/13.mp4';
import reel_poster_13 from '../../lucas-content/Instagram Reel/13.jpg';
import reel_14 from '../../lucas-content/Instagram Reel/14.mp4';
import reel_poster_14 from '../../lucas-content/Instagram Reel/14.jpg';
import reel_15 from '../../lucas-content/Instagram Reel/15.mp4';
import reel_poster_15 from '../../lucas-content/Instagram Reel/15.jpg';
import reel_16 from '../../lucas-content/Instagram Reel/16.mp4';
import reel_poster_16 from '../../lucas-content/Instagram Reel/16.jpg';

export const projects = [
    {
        "id": 100,
        "title": "Converse",
        "category": "commercial",
        "role": "spark_me",
        "date": {
            "fr": "December 2025",
            "en": "December 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Publicité spec développée dans un cadre étudiant, pensée comme une immersion dans des conditions de production réelles. Le tournage s’est déroulé entièrement sous la pluie, impliquant une organisation précise et une rigueur technique constante. L’image s’appuie sur une esthétique brute et contrastée, en lien direct avec l’énergie urbaine de la marque.",
            "en": "Spec commercial developed in a student context, designed as an immersion into real production conditions. Shot entirely under rain, the project required precise organization and constant technical control. The visuals rely on a raw, contrasted aesthetic aligned with the brand’s urban energy."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_0_A,
        "collection": [
            {
                "type": "image",
                "src": proj_0_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_0_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_0_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_0_D,
                "poster": ""
            }
        ]
    },
    {
        "id": 101,
        "title": "Fishermen Friends",
        "category": "commercial",
        "role": "spark_me",
        "date": {
            "fr": "December 2025",
            "en": "December 2025"
        },
        "status": "Completed",
        "link": "https://www.instagram.com/reel/DVTdTtMjHt5/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
        "desc": {
            "fr": "Publicité spec tournée intégralement en studio, construite autour d’un décor surélevé exigeant une grande précision d’exécution. Le projet repose sur une mise en scène structurée et une attention particulière portée à la cohérence visuelle dans un environnement technique contraignant.",
            "en": "Studio-shot spec commercial built around an elevated set requiring a high level of execution precision. The project relies on structured staging and strong visual consistency within a technically demanding environment."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_1_A,
        "collection": [
            {
                "type": "image",
                "src": proj_1_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_1_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_1_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_1_D,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_1_E,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_1_F,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_1_G,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_1_H,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_1_I,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_1_J,
                "poster": ""
            }
        ]
    },
    {
        "id": 102,
        "title": "The Street Partners",
        "category": "commercial",
        "role": "dop_me",
        "date": {
            "fr": "July 2025",
            "en": "July 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Film publicitaire corporate réalisé pour The Street Partners. Une approche visuelle sobre et contemporaine, pensée pour valoriser le branding et transmettre une image professionnelle claire, élégante et maîtrisée.",
            "en": "Corporate commercial created for The Street Partners. A clean, contemporary visual approach designed to enhance branding and convey a clear, elegant and controlled professional image."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_2_A,
        "collection": [
            {
                "type": "image",
                "src": proj_2_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_2_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_2_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_2_D,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_2_E,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_2_F,
                "poster": ""
            }
        ]
    },
    {
        "id": 103,
        "title": "Bergers des Abeilles",
        "category": "documentary",
        "role": "dop_me",
        "date": {
            "fr": "April 2025",
            "en": "April 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Documentaire destiné aux festivals, suivant le quotidien d’apiculteurs et mettant en lumière le rôle fondamental des abeilles. Le film adopte une approche immersive, ancrée dans le terrain, laissant une large place aux gestes, aux paysages et au temps long.",
            "en": "Festival-oriented documentary following the daily lives of beekeepers and highlighting the essential role of bees. The film adopts an immersive, field-driven approach, giving space to gestures, landscapes and the passage of time."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_3_A,
        "collection": [
            {
                "type": "image",
                "src": proj_3_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_3_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_3_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_3_D,
                "poster": ""
            }
        ]
    },
    {
        "id": 104,
        "title": "Des collines aux machines",
        "category": "documentary",
        "role": "director_me",
        "date": {
            "fr": "May 2025",
            "en": "May 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Documentaire destiné aux festivals consacré aux bergers contemporains et aux mutations de leur mode de vie. Le film explore la cohabitation entre pratiques traditionnelles et outils modernes, dessinant le portrait d’un monde rural en transition.",
            "en": "Festival-oriented documentary focusing on contemporary shepherds and the transformation of their way of life. The film explores the coexistence of traditional practices and modern tools, portraying a rural world in transition."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_4_A,
        "collection": [
            {
                "type": "image",
                "src": proj_4_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_4_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_4_C,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_4_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_4_E,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_4_F,
                "poster": ""
            }
        ]
    },
    {
        "id": 105,
        "title": "Bonne Santé – Visualiser",
        "category": "music_video",
        "role": "dop_me",
        "date": {
            "fr": "August 2025",
            "en": "August 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Visualiser musical pour Faz’r Elengi, conçu autour d’un dispositif volontairement minimal. L’image se concentre sur la présence de l’artiste, le rythme et l’atmosphère, dans une recherche de clarté et de cohérence esthétique.",
            "en": "Music visualizer for Faz’r Elengi, designed around a deliberately minimal setup. The visuals focus on the artist’s presence, rhythm and atmosphere, aiming for clarity and aesthetic coherence."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_5_A,
        "collection": [
            {
                "type": "image",
                "src": proj_5_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_5_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_5_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_5_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_5_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 106,
        "title": "Jamais",
        "category": "music_video",
        "role": "dop_me",
        "date": {
            "fr": "November 2024",
            "en": "November 2024"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Clip musical pour Faz’r Elengi, tourné en studio d’enregistrement. Une approche directe et épurée, pensée pour exploiter au maximum un espace restreint et des moyens volontairement limités.",
            "en": "Music video for Faz’r Elengi, shot in a recording studio. A direct, stripped-down approach designed to fully exploit a confined space and intentionally limited resources."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_6_A,
        "collection": [
            {
                "type": "image",
                "src": proj_6_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_6_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_6_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_6_D,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_6_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 107,
        "title": "Komani",
        "category": "music_video",
        "role": "director_me",
        "date": {
            "fr": "August 2025",
            "en": "August 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Clip musical pour Faz’r Elengi, tourné dans plusieurs lieux aux ambiances contrastées. Le projet combine narration visuelle, énergie brute et séquences techniques plus complexes, afin de construire un univers fort et rythmé.",
            "en": "Music video for Faz’r Elengi, shot across multiple locations with contrasting atmospheres. The project combines visual storytelling, raw energy and more complex technical sequences to build a strong, dynamic universe."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_7_cover,
        "collection": [
            {
                "type": "image",
                "src": proj_7_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_7_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_7_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_7_D,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_7_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 108,
        "title": "Level Up",
        "category": "music_video",
        "role": "cam_dir_me",
        "date": {
            "fr": "September 2025",
            "en": "September 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Clip musical pour l’artiste VIO, porté par une énergie constante et un rythme soutenu. L’univers visuel mêle danse, performance et contrastes marqués, au service d’une identité affirmée.",
            "en": "Music video for the artist VIO, driven by constant energy and a strong sense of rhythm. The visual universe blends dance, performance and bold contrasts in support of a confident identity."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_8_A,
        "collection": [
            {
                "type": "image",
                "src": proj_8_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_8_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_8_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_8_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_8_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 109,
        "title": "Dîner d’Affaire",
        "category": "short_film",
        "role": "spark_me",
        "date": {
            "fr": "November 2025",
            "en": "November 2025"
        },
        "status": "Completed",
        "link": "https://youtu.be/XE4fg93ZOfc",
        "desc": {
            "fr": "Court-métrage réalisé dans le cadre du 48h Côte d’Azur, sur le thème « Repas ». Le film met en scène une confrontation intime et tendue entre une artiste et son producteur, explorant les rapports de pouvoir et la manipulation.",
            "en": "Short film created for the 48h Côte d’Azur competition, on the theme “Dinner.” The story stages an intimate, tense confrontation between an artist and her producer, exploring power dynamics and manipulation."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_9_A,
        "collection": [
            {
                "type": "image",
                "src": proj_9_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_9_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_9_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_9_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_9_E,
                "poster": ""
            }
        ]
    },
    {
        "id": 110,
        "title": "Fort Intérieur",
        "category": "short_film",
        "role": "dop_me",
        "date": {
            "fr": "June 2025",
            "en": "June 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Court-métrage étudiant centré sur l’héritage familial et les traumatismes enfouis. À travers un lieu chargé de mémoire, le film suit un personnage confronté à un passé qu’il ne peut plus ignorer. Court-métrage réalisé pour le Nikon Film Festival 2025. Le film explore la transmission, l’image de soi et les liens intergénérationnels à travers une approche sensible et introspective.",
            "en": "Student short film centered on family heritage and buried trauma. Through a memory-laden location, the film follows a character forced to confront a past he can no longer ignore. Le miroir des générations – Nikon Film Festival 2025 Short film created for the Nikon Film Festival 2025. The film explores transmission, self-image and intergenerational bonds through a sensitive, introspective approach."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_10_A,
        "collection": [
            {
                "type": "image",
                "src": proj_10_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_10_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_10_C,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_10_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_10_E,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_10_F,
                "poster": ""
            }
        ]
    },
    {
        "id": 111,
        "title": "Léo",
        "category": "short_film",
        "role": "camera_op_me",
        "date": {
            "fr": "December 2024",
            "en": "December 2024"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Court-métrage réalisé pour le Nikon Film Festival 2025, sur le thème « Super-héros ». Le récit suit un jeune garçon en situation de handicap qui réinvente son quotidien par l’imaginaire, en se projetant dans les héros de ses bandes dessinées.",
            "en": "Short film created for the Nikon Film Festival 2025, on the theme “Superhero.” The story follows a disabled young boy who reimagines his everyday life through imagination, projecting himself into the heroes of his comic books."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_11_A,
        "collection": [
            {
                "type": "image",
                "src": proj_11_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_11_B,
                "poster": ""
            }
        ]
    },
    {
        "id": 112,
        "title": "Marcello",
        "category": "short_film",
        "role": "key_grip_me",
        "date": {
            "fr": "September 2025",
            "en": "September 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Court-métrage destiné aux festivals, produit en association. Le film plonge dans le milieu du journalisme niçois des années 1980, avec une attention particulière portée à l’atmosphère, au contexte historique et aux tensions de l’époque.",
            "en": "Festival-oriented short film produced through a non-profit association. Set in the world of Nice journalism in the 1980s, with close attention to atmosphere, historical context and period tensions."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_12_A,
        "collection": [
            {
                "type": "image",
                "src": proj_12_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_12_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_12_C,
                "poster": ""
            }
        ]
    },
    {
        "id": 113,
        "title": "Nouvelle Ecoute",
        "category": "short_film",
        "role": "camera_op_me",
        "date": {
            "fr": "November 2025",
            "en": "November 2025"
        },
        "status": "Delivered",
        "link": "https://www.youtube.com/watch?v=0o7v2v1dPTc",
        "desc": {
            "fr": "Court-métrage réalisé dans le cadre du festival TousHanscène. Le film suit un jeune homme sourd privé de ses appareils auditifs, confronté à une succession d’obstacles dans un environnement peu adapté à sa réalité. Le récit adopte un point de vue immersif, mettant en tension le quotidien et l’isolement sensoriel.",
            "en": "Festival-oriented short film created for the TousHanscène Festival. The film follows a deaf young man who loses his hearing aids and faces a series of obstacles in an environment poorly adapted to his reality. The narrative adopts an immersive perspective, emphasizing everyday tension and sensory isolation."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_13_A,
        "collection": [
            {
                "type": "image",
                "src": proj_13_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_13_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_13_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_13_D,
                "poster": ""
            }
        ]
    },
    {
        "id": 114,
        "title": "Parles-moi",
        "category": "short_film",
        "role": "gaffer_me",
        "date": {
            "fr": "November 2025",
            "en": "November 2025"
        },
        "status": "Completed",
        "link": "https://youtu.be/LFv09FZMiSM",
        "desc": {
            "fr": "Court-métrage réalisé pour le Nikon Film Festival 2025. Le film explore la fragilité d’un couple confronté à une hospitalisation soudaine, en s’attachant aux silences, aux regards et à l’intimité émotionnelle.",
            "en": "Short film created for the Nikon Film Festival 2025. The film explores the fragility of a couple facing a sudden hospitalization, focusing on silence, glances and emotional intimacy."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_14_A,
        "collection": [
            {
                "type": "image",
                "src": proj_14_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_14_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_14_C,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_14_D,
                "poster": ""
            }
        ]
    },
    {
        "id": 115,
        "title": "Transmission",
        "category": "short_film",
        "role": "dop_me",
        "date": {
            "fr": "December 2025",
            "en": "December 2025"
        },
        "status": "Completed",
        "link": "https://youtu.be/-Emi3lXQOys",
        "desc": {
            "fr": "Court-métrage réalisé pour le Nikon Film Festival 2025. Le film explore les notions de transmission, de perception de soi et de liens intergénérationnels, à travers une approche sensible et introspective, centrée sur le regard que l’on porte sur les autres et sur soi-même.",
            "en": "Short film created for the Nikon Film Festival 2025. The film explores themes of transmission, self-perception and intergenerational relationships through a sensitive, introspective approach focused on how we view others and ourselves."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_15_A,
        "collection": [
            {
                "type": "image",
                "src": proj_15_A,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_15_B,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_15_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_15_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_15_F,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_15_G,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_15_H,
                "poster": ""
            }
        ]
    },
    {
        "id": 116,
        "title": "Nassim Boukrouh",
        "category": "social_media",
        "role": "camera_op_me",
        "date": {
            "fr": "2025",
            "en": "2025"
        },
        "status": "Completed",
        "link": "",
        "desc": {
            "fr": "Série de vidéos YouTube dédiées à l’immobilier, tournée à l’international, notamment en Afrique du Sud, en Suisse, en France, au Canada et aux Émirats arabes unis. Un format mobile et dynamique, pensé pour s’adapter à des contextes variés tout en restant accessible et informatif.",
            "en": "YouTube video series focused on real estate, shot internationally across South Africa, Switzerland, France, Canada and the United Arab Emirates. A mobile, dynamic format designed to adapt to diverse contexts while remaining accessible and informative."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_16_A,
        "collection": [
            {
                "type": "image",
                "src": proj_16_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_16_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_16_C,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_16_D,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_16_E,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_16_F,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_16_G,
                "poster": ""
            }
        ]
    },
    {
        "id": 117,
        "title": "M&L",
        "category": "wedding",
        "role": "dop_me",
        "date": {
            "fr": "July 2025",
            "en": "July 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Film de mariage tourné au Mas des 5 Fontaines. Une approche sensible mêlant captation documentaire et écriture cinématographique, cherchant à retranscrire l’émotion, les détails et l’atmosphère de la journée.",
            "en": "Wedding film shot at Mas des 5 Fontaines. A sensitive approach blending documentary capture and cinematic storytelling, aiming to convey emotion, detail and the atmosphere of the day."
        },
        "credits": "",
        "structuredCredits": [],
        "media": proj_17_A,
        "collection": [
            {
                "type": "image",
                "src": proj_17_A,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_17_B,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_17_C,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_17_D,
                "poster": ""
            },
            {
                "type": "image",
                "src": proj_17_E,
                "poster": ""
            },
            {
                "type": "video",
                "src": proj_17_F,
                "poster": ""
            }
        ]
    },
    {
        "id": 10,
        "title": "Instagram Reels",
        "category": "social_media",
        "role": "content_creation_me",
        "date": {
            "fr": "2025",
            "en": "2025"
        },
        "status": "Online",
        "link": "",
        "desc": {
            "en": "A collection of dynamic, high-engagement reels created for various brands and personal projects.",
            "fr": "Une collection de reels dynamiques créés pour diverses marques et projets personnels."
        },
        "media": "/lucas/assets/projects/instagram-3d-final.png",
        "type": "collection",
        "collection": [
            {
                "type": "video",
                "src": reel_1,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_1
            },
            {
                "type": "video",
                "src": reel_2,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_2
            },
            {
                "type": "video",
                "src": reel_3,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_3
            },
            {
                "type": "video",
                "src": reel_4,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_4
            },
            {
                "type": "video",
                "src": reel_5,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_5
            },
            {
                "type": "video",
                "src": reel_6,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_6
            },
            {
                "type": "video",
                "src": reel_7,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_7
            },
            {
                "type": "video",
                "src": reel_8,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_8
            },
            {
                "type": "video",
                "src": reel_9,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_9
            },
            {
                "type": "video",
                "src": reel_10,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_10
            },
            {
                "type": "video",
                "src": reel_11,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_11
            },
            {
                "type": "video",
                "src": reel_12,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_12
            },
            {
                "type": "video",
                "src": reel_13,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_13
            },
            {
                "type": "video",
                "src": reel_14,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_14
            },
            {
                "type": "video",
                "src": reel_15,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_15
            },
            {
                "type": "video",
                "src": reel_16,
                "title": {
                    "fr": "",
                    "en": ""
                },
                "poster": reel_poster_16
            }
        ]
    }
];
