
// AUTO-GENERATED BY scripts/mariage/generate-data.cjs
// DO NOT EDIT MANUALLY - UPDATE info.txt FILES IN STOCK

import w_0_A from '../../mariage-content/chloe-alexandre/A.jpg';
import w_0_B from '../../mariage-content/chloe-alexandre/B.jpg';
import w_0_C from '../../mariage-content/chloe-alexandre/C.mp4';
import w_0_D from '../../mariage-content/chloe-alexandre/D.jpg';
import w_0_E from '../../mariage-content/chloe-alexandre/E.jpg';
import w_0_F from '../../mariage-content/chloe-alexandre/F.mp4';
import w_1_A from '../../mariage-content/elodie-julien/A.jpg';
import w_1_B from '../../mariage-content/elodie-julien/B.jpg';
import w_1_C from '../../mariage-content/elodie-julien/C.jpg';
import w_2_A from '../../mariage-content/sarah-thomas/A.jpg';
import w_2_B from '../../mariage-content/sarah-thomas/B.jpg';
import w_2_C from '../../mariage-content/sarah-thomas/C.jpg';

export const weddings = [
    {
        "id": 1,
        "title": "MARION & LUCIEN",
        "subtitle": "THE PROVENCE EDIT",
        "link": "https://youtu.be/P_eesdexjfs?si=2KAz39jzmFFlfHg_",
        "description": {
            "fr": "Un road-trip émotionnel à travers la Provence. Des champs de lavande aux vieilles pierres, une ode à l'amour intemporel et à la lumière du sud.",
            "en": "An emotional road trip through Provence. From lavender fields to ancient stones, an ode to timeless love and southern light."
        },
        "media": [
            w_0_A,
            w_0_B,
            w_0_C,
            w_0_D,
            w_0_E,
            w_0_F
        ]
    },
    {
        "id": 2,
        "title": "ELODIE & JULIEN",
        "subtitle": "THE PARISIAN EDIT",
        "link": "",
        "description": {
            "fr": "L'amour au cœur de la ville lumière. Une atmosphère urbaine, sophistiquée et terriblement romantique.",
            "en": "Love in the heart of the City of Light. A sophisticated, urban, and terribly romantic atmosphere."
        },
        "media": [
            w_1_A,
            w_1_B,
            w_1_C
        ]
    },
    {
        "id": 3,
        "title": "SARAH & THOMAS",
        "subtitle": "THE RIVIERA EDIT",
        "link": "",
        "description": {
            "fr": "L'élégance de la Côte d'Azur. Une célébration chic et solaire, bercée par le bruit des vagues et l'éclat du soleil méditerranéen.",
            "en": "The elegance of the French Riviera. A chic and sunny celebration, rocked by the sound of waves and the sparkle of the Mediterranean sun."
        },
        "media": [
            w_2_A,
            w_2_B,
            w_2_C
        ]
    }
];
