
// AUTO-GENERATED BY scripts/generate-data.js
// DO NOT EDIT MANUALLY - UPDATE info.txt FILES INSTEAD

import proj_5_A from '../Contents projets/Projets/Music Video/Bonne Santé – Visualiser/A.png';
import proj_6_A from '../Contents projets/Projets/Music Video/Jamais/A.png';
import proj_8_A from '../Contents projets/Projets/Music Video/Level Up/A.png';
import proj_10_A from '../Contents projets/Projets/Short Film/Fort Intérieur/A.png';
import proj_17_A from '../Contents projets/Projets/Weddings/M&L/A.png';

export const projects = [
    {
        "id": 100,
        "title": "Converse",
        "category": "commercial",
        "role": "Electrician",
        "date": {
            "fr": "December 2025",
            "en": "December 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Publicité (Spec Ad) réalisée par une équipe de l'ESRA. Un tournage entièrement sous la pluie, nécessitant une gestion électrique rigoureuse et sécurisée. J'y ai travaillé comme renfort Électro.",
            "en": "Spec ad by an ESRA team, shot entirely under rain. Required strict, safe electrical handling. I worked as Electrician reinforcement."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 101,
        "title": "Fishermen Friends",
        "category": "commercial",
        "role": "Grip",
        "date": {
            "fr": "December 2025",
            "en": "December 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Publicité (Spec Ad) produite par une équipe de l'ESRA, tournée entièrement en studio. Un décor surélevé qui exigeait une grande rigueur technique. J'ai occupé les postes d'Électro et Machiniste.",
            "en": "Studio-shot ESRA spec ad with an elevated set requiring technical precision. I worked as both Electrician and Grip."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 102,
        "title": "The Street Partners",
        "category": "commercial",
        "role": "Director of Photography",
        "date": {
            "fr": "July 2025",
            "en": "July 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Publicité pour The Street Partners. Une approche corporate moderne axée sur le branding et une image soignée. J'étais Directeur de la Photographie.",
            "en": "Corporate commercial for The Street Partners, built with a modern visual identity focused on clean branding. I was Director of Photography."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 103,
        "title": "Bergers des Abeilles",
        "category": "documentary",
        "role": "Director of Photography",
        "date": {
            "fr": "April 2025",
            "en": "April 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Documentaire de festival suivant des apiculteurs et le rôle vital des abeilles. Un film ancré dans le travail de terrain et l'artisanat traditionnel. J'étais Directeur de la Photographie et Cadreur.",
            "en": "Festival documentary following beekeepers and the crucial role of bees. Rooted in real fieldwork and traditional craft. I worked as Director of Photography and Camera Operator."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 104,
        "title": "Des collines aux machines",
        "category": "documentary",
        "role": "Director",
        "date": {
            "fr": "May 2025",
            "en": "May 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Documentaire de festival sur les bergers modernes et les défis qu'ils affrontent aujourd'hui. Un regard authentique sur la tension entre tradition et modernité. J'ai réalisé le film.",
            "en": "Festival documentary about modern shepherds facing the tension between tradition and technological evolution. I directed the film."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 105,
        "title": "Bonne Santé – Visualiser",
        "category": "music_video",
        "role": "Director of Photography",
        "date": {
            "fr": "August 2025",
            "en": "August 2025"
        },
        "status": "Delivered",
        "link": "https://youtu.be/tgxDICtOiC8?si=0VFyGOwveazqQdd4",
        "desc": {
            "fr": "Visualizer musical pour Faz’r Elengi. Un concept épuré et ciblé, centré sur la performance et l'esthétique. J'étais Directeur de la Photographie.",
            "en": "Music visualizer for Faz’r Elengi, built around a clean performance-driven aesthetic. I worked as Director of Photography."
        },
        "media": proj_5_A,
        "collection": [
            {
                "type": "image",
                "src": proj_5_A,
                "poster": ""
            }
        ]
    },
    {
        "id": 106,
        "title": "Jamais",
        "category": "music_video",
        "role": "Director of Photography",
        "date": {
            "fr": "November 2024",
            "en": "November 2024"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Clip vidéo pour Faz’r Elengi tourné en studio d'enregistrement. Une création simple mais efficace avec très peu de matériel. J'étais Directeur de la Photographie.",
            "en": "Minimalist studio-shot music video for Faz’r Elengi, created with very limited equipment. I worked as Director of Photography."
        },
        "media": proj_6_A,
        "collection": [
            {
                "type": "image",
                "src": proj_6_A,
                "poster": ""
            }
        ]
    },
    {
        "id": 107,
        "title": "Komani",
        "category": "music_video",
        "role": "Director",
        "date": {
            "fr": "August 2025",
            "en": "August 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Clip vidéo pour l'artiste Faz’r Elengi. Tourné dans quatre lieux différents, avec notamment ma première gestion de voitures de drift sur le plateau. J'ai réalisé le clip et supervisé toute la mise en scène.",
            "en": "Music video for Faz’r Elengi shot in four locations, including my first experience supervising drift cars on set. I directed and handled staging."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 108,
        "title": "Level Up",
        "category": "music_video",
        "role": "Camera Operator & Director",
        "date": {
            "fr": "September 2025",
            "en": "September 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Clip vidéo pour l'artiste VIO. Un univers dynamique mêlant danse, rythme et une identité visuelle marquante. J'ai réalisé le vidéo.",
            "en": "Energetic music video for VIO, mixing dance, rhythm and strong visual identity. I directed the video and operated camera."
        },
        "media": proj_8_A,
        "collection": [
            {
                "type": "image",
                "src": proj_8_A,
                "poster": ""
            }
        ]
    },
    {
        "id": 109,
        "title": "Dîner d’Affaire",
        "category": "short_film",
        "role": "Electrician",
        "date": {
            "fr": "November 2025",
            "en": "November 2025"
        },
        "status": "In Distribution",
        "link": "https://youtu.be/XE4fg93ZOfc",
        "desc": {
            "fr": "Court-métrage tourné pour le 48h Côte d’Azur, sur le thème « Repas ». L'histoire suit une artiste qui confronte son producteur toxique. Initialement engagé comme Électro, j'ai finalement pris en charge toute la machinerie durant le tournage.",
            "en": "Short film for the 48h Côte d’Azur contest, on the theme “Dinner.” The story follows an artist confronting her toxic producer. Initially hired as Electrician, I ended up taking full charge of the grip department on set."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 110,
        "title": "Fort Intérieur",
        "category": "short_film",
        "role": "Director of Photography",
        "date": {
            "fr": "June 2025",
            "en": "June 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Court-métrage d'un étudiant de Studio M. L'histoire d'un jeune homme héritant de la maison familiale et confrontant un traumatisme enfoui. J'ai travaillé comme Directeur de la Photographie.",
            "en": "Short film by a Studio M student. The story follows a young man confronting inherited trauma in his family home. I was Director of Photography."
        },
        "media": proj_10_A,
        "collection": [
            {
                "type": "image",
                "src": proj_10_A,
                "poster": ""
            }
        ]
    },
    {
        "id": 111,
        "title": "Le miroir des générations",
        "category": "short_film",
        "role": "Director of Photography",
        "date": {
            "fr": "December 2025",
            "en": "December 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Court-métrage réalisé pour le Nikon Film Festival sur le thème « Le Feu ». Le film explore la transmission, la perception de soi et les liens intergénérationnels. J'étais Directeur de la Photographie.",
            "en": "Short film for the Nikon Film Festival, on the theme “Beauty.” The film explores transmission, self-perception and generational transitions. I was Director of Photography."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 112,
        "title": "Léo",
        "category": "short_film",
        "role": "Camera Operator",
        "date": {
            "fr": "December 2024",
            "en": "December 2024"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Court-métrage pour le Nikon Film Festival 2024, thème « Super-héros ». Un jeune garçon handicapé imagine marcher comme dans ses comics préférés. J'étais Cadreur.",
            "en": "Short film for the 2024 Nikon Film Festival, theme “Superhero.” A disabled boy imagines himself walking like the characters from his comics. I worked as Camera Operator."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 113,
        "title": "Marcello",
        "category": "short_film",
        "role": "Key Grip",
        "date": {
            "fr": "September 2025",
            "en": "September 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Court-métrage réalisé pour des festivals, produit en association. L'histoire plonge dans le monde du journalisme niçois des années 1980. J'y ai travaillé comme Chef Machiniste, encadrant une équipe de 2 à 4 techniciens, de la pré-production à l'intense travail de plateau.",
            "en": "Short film made for festivals under a non-profit association. Set in the world of Nice journalism in the 1980s. I worked as Key Grip, managing a team of 2 to 4 technicians through prep and a demanding shoot."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 114,
        "title": "Nouvelle Ecoute",
        "category": "short_film",
        "role": "Camera Operator",
        "date": {
            "fr": "November 2025",
            "en": "November 2025"
        },
        "status": "Delivered",
        "link": "",
        "desc": {
            "fr": "Court-métrage pour le Festival TousHanscene. Un jeune sourd perd ses appareils auditifs et fait face à une journée d'obstacles. J'étais Cadreur.",
            "en": "Short film for the TousHanscene Festival. A deaf young man loses his hearing aids and must navigate a difficult day. I worked as Camera Operator."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 115,
        "title": "Parles-moi",
        "category": "short_film",
        "role": "Gaffer",
        "date": {
            "fr": "November 2025",
            "en": "November 2025"
        },
        "status": "In Editing",
        "link": "",
        "desc": {
            "fr": "Court-métrage pour le Nikon 2025. Un couple déstabilisé par une hospitalisation soudaine, naviguant entre fragilité et intimité. J'étais Chef Électricien (Gaffer), créant une lumière douce et émotionnelle.",
            "en": "Short film for the Nikon Film Festival 2025, theme “Beauty.” A couple faces emotional fragility after a sudden hospitalisation. I crafted a soft, intimate lighting setup."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 116,
        "title": "Nassim Boukrouh",
        "category": "social_media",
        "role": "Camera Operator",
        "date": {
            "fr": "Current",
            "en": "Current"
        },
        "status": "Ongoing",
        "link": "https://youtube.com/@nassimboukrouh?si=zvPcrKR7CY8gO8xt",
        "desc": {
            "fr": "Série de vidéos YouTube pour un créateur de contenu immobilier. Tournages mobiles à travers la Suisse dans des environnements variés. J'étais Cadreur.",
            "en": "YouTube real-estate content shot across Switzerland in various environments. I worked as Camera Operator."
        },
        "media": "https://picsum.photos/seed/placeholder/800/600",
        "collection": null
    },
    {
        "id": 117,
        "title": "M&L",
        "category": "wedding",
        "role": "Director of Photography",
        "date": {
            "fr": "July 2025",
            "en": "July 2025"
        },
        "status": "Delivered",
        "link": "https://youtu.be/P_eesdexjfs?si=2KAz39jzmFFlfHg_",
        "desc": {
            "fr": "Film de mariage tourné au Mas des 5 Fontaines. Un mélange entre captation documentaire et approche cinématographique. J'étais Cadreur et Directeur de la Photographie.",
            "en": "Wedding film shot at Mas des 5 Fontaines, blending documentary capture and cinematic language. I worked as Camera Operator and Director of Photography."
        },
        "media": proj_17_A,
        "collection": [
            {
                "type": "image",
                "src": proj_17_A,
                "poster": ""
            }
        ]
    },
    {
        "id": 10,
        "title": "Instagram Reels",
        "category": "social_media",
        "role": "Content Creation",
        "date": {
            "fr": "2025",
            "en": "2025"
        },
        "status": "Online",
        "link": "",
        "desc": {
            "en": "A collection of dynamic, high-engagement reels created for various brands and personal projects.",
            "fr": "Une collection de reels dynamiques créés pour diverses marques et projets personnels."
        },
        "media": "assets/projects/instagram-3d-final.png",
        "type": "collection",
        "collection": [
            {
                "type": "video",
                "src": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
                "title": {
                    "fr": "Fashion Week",
                    "en": "Fashion Week"
                },
                "poster": "https://picsum.photos/seed/v1/260/460"
            },
            {
                "type": "video",
                "src": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
                "title": {
                    "fr": "Urban Explorer",
                    "en": "Urban Explorer"
                },
                "poster": "https://picsum.photos/seed/v2/260/460"
            },
            {
                "type": "video",
                "src": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
                "title": {
                    "fr": "Neon Nights",
                    "en": "Neon Nights"
                },
                "poster": "https://picsum.photos/seed/v3/260/460"
            },
            {
                "type": "video",
                "src": "https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
                "title": {
                    "fr": "Cinematic Port",
                    "en": "Cinematic Port"
                },
                "poster": "https://picsum.photos/seed/v4/260/460"
            },
            {
                "type": "video",
                "src": "https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
                "title": {
                    "fr": "Vitesse",
                    "en": "Speed"
                },
                "poster": "https://picsum.photos/seed/v5/260/460"
            },
            {
                "type": "video",
                "src": "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
                "title": {
                    "fr": "Sci-Fi Mood",
                    "en": "Sci-Fi Mood"
                },
                "poster": "https://picsum.photos/seed/v6/260/460"
            }
        ]
    }
];
